#!/bin/sh
exec rep "$0" "$@"
!#

(require 'gui.gtk-2.libglade))

(when (get-command-line-option "--gnome")
  (require 'gui.gtk-2.gnomeui)
  (gnome-init "test-libglade" "0.0"))

(let
    ((xml (or (glade-xml-new (car command-line-args))
	      (error "something bad happened while creating the interface"))))

  (glade-xml-signal-autoconnect xml)
  (gtk-main))

(throw 'quit 0)

;; Local variables:
;; major-mode: lisp-mode
;; End:
